kind: Deployment
apiVersion: apps/v1
metadata: 
  name: crudservice-deployment
  namespace: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudservice
  template:
    metadata:
      labels:
        app: crudservice
    spec:
      containers: 
        - name: crudservice-container 
          image: udaykumar550/crudservice:latest
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CRUDSERVICE_PORT
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CRUDSERVICE_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CRUDSERVICE_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: MYSQL_ROOT_PASSWORD
