kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels: 
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: udaykumar550/frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 70m
              memory: 256Mi
