apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: userservice-mysql-vpa
  namespace: crud
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: userservice-mysql-statefulset
  updatePolicy:
    updateMode: "Auto"   # Disadvantage if we do auto there might be downtime.
